export const SET_TEST_THUMBANAIL = "SET_TEST_THUMBNAIL" as const;
export const ROTATE_SET_THUMBNAIL = "ROTATE_SET_THUMBNAIL" as const;
export const TARGET_SET_THUMBNAIL = "TARGET_SET_THUMBNAIL" as const;
export const SET_USERDATA_REQUEST = "SET_USERDATA_REQUEST" as const;
