name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - run: npm install
    - run: npm run test
    - run: npm run build --if-present
      env:
        CI: true
